#!/bin/env python3
from argparse import ArgumentParser
import subprocess as sp
import os
import sys

comsa_modulepath = "modulepath:/comsa.pkl"
comsa_extends = "extends \"modulepath:/comsa.pkl\""
comsa_amends = "amends \"modulepath:/comsa.pkl\""

executable_list = [
"compose2diagram",
"compose2k8s",
"compose2yaml",
"compose-check",
"compose-metrics",
"comsa2compose",
"comsa2compose-yaml",
"comsa2k8s",
"comsa2yaml",
"comsa-analysis",
"comsa-check",
"comsa-metrics",
"comsa-scattering",
"comsa-tangling",
"comsa-type-scattering",
"hypercomsa",
"pkl-eval",
"topology"
]

# COMMAND LINE ARGUMENT PARSER
argument_parser = ArgumentParser(
        prog = 'COMSA toolbox',
        description = 'Toolbox for the Concern Oriented MicroService Architecture language.')

argument_parser.add_argument("-o", default=False, type=str, help="Output file, stdout if not set")
argument_parser.add_argument("--executables_folder_path", default="./bin/", type=str, help="Executables folder path")
argument_parser.add_argument("executable", choices=executable_list, help="Select a tool among {}".format((", ").join(executable_list)))
argument_parser.add_argument("input_file", help="Input file")
args = vars(argument_parser.parse_args())

os.environ['PATH'] += os.pathsep + args["executables_folder_path"]

filepath = args['input_file']

if os.path.splitext(filepath)[1] == ".comsa":
    sp.run(["cp", args["input_file"], "/tmp"])
    filepath = os.path.join("/tmp", os.path.basename(args['input_file']))
    with open(filepath, "r") as file:
        lines = file.readlines()
    if comsa_modulepath not in "".join(lines):
        lines.insert(0, comsa_extends)
        with open(filepath, "w") as file:
            file.writelines(lines)

if args["executable"] == "hypercomsa":
    ret = sp.run([os.path.join(args["executables_folder_path"], args["executable"]), filepath, args['o']], capture_output=True, text=True)
    exit(ret.returncode)
elif args["executable"] == "topology":
    ret = sp.run([os.path.join(args["executables_folder_path"], args["executable"]), filepath, args['o']], capture_output=True, text=True)
    exit(ret.returncode)
elif args["executable"] == "pkl-eval":
    ret = sp.run([os.path.join(args["executables_folder_path"], "pkl"), "eval", "--module-path", "./modules/", filepath], capture_output=True, text=True)
else:
    ret = sp.run([os.path.join(args["executables_folder_path"], args["executable"]), filepath], capture_output=True, text=True)

if ret.returncode != 0:
    print(ret.stderr, file=sys.stderr)
    exit(ret.returncode)

if args["o"]:
    with open(args["o"], "w") as f:
        print(ret.stdout, file=f)
        exit(0)

print(ret.stdout, file=sys.stdout)
exit(0)
